# Generated by Django 5.0.6 on 2026-05-04 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kit_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('kit_name', models.CharField(blank=True, max_length=200)),
                ('service', models.CharField(blank=True, max_length=200)),
                ('observations', models.TextField(blank=True)),
                ('instruments', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sf_kits',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kit_name_snapshot', models.CharField(blank=True, max_length=200)),
                ('reporter_nom', models.CharField(max_length=100)),
                ('reporter_prenom', models.CharField(max_length=100)),
                ('reporter_service', models.CharField(max_length=200)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High (Urgent)')], default='medium', max_length=10)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved')], default='new', max_length=10)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('kit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='kits.kit', to_field='kit_id')),
            ],
            options={
                'db_table': 'sf_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
