from rest_framework import serializers
from .models import Kit, Report




class KitListSerializer(serializers.ModelSerializer):
    """Compact — used when listing all kits (edit.html picker grid)."""
    instrument_count = serializers.SerializerMethodField()
    created_by_name  = serializers.SerializerMethodField()

    class Meta:
        model  = Kit
        fields = [
            'kit_id', 'kit_name', 'service', 'status',
            'instrument_count', 'created_by_name',
            'created_at', 'updated_at',
        ]

    def get_instrument_count(self, obj):
        return len(obj.instruments) if isinstance(obj.instruments, list) else 0

    def get_created_by_name(self, obj):
        return obj.created_by.full_name if obj.created_by else 'Unknown'


class KitDetailSerializer(serializers.ModelSerializer):
    """Full detail — used for viewer.html and edit.html edit view."""
    created_by_name = serializers.SerializerMethodField()

    class Meta:
        model  = Kit
        fields = [
            'kit_id', 'kit_name', 'service', 'instruments',
            'observations', 'status', 'created_by_name',
            'created_at', 'updated_at',
        ]
        read_only_fields = ['created_at', 'updated_at']

    def get_created_by_name(self, obj):
        return obj.created_by.full_name if obj.created_by else 'Unknown'


class KitCreateUpdateSerializer(serializers.ModelSerializer):
    """
    Used for create (index.html) and update (edit.html save).
    Accepts the kit_id generated by the frontend.
    """

    class Meta:
        model  = Kit
        fields = [
            'kit_id', 'kit_name', 'service',
            'instruments', 'observations',
        ]

    def validate_instruments(self, value):
        if not isinstance(value, list):
            raise serializers.ValidationError('instruments must be a JSON array.')
        return value

    def create(self, validated_data):
        request = self.context.get('request')
        kit = Kit(**validated_data)
        if request and request.user and request.user.is_authenticated:
            kit.created_by = request.user
        kit.save()
        return kit




class ReportCreateSerializer(serializers.ModelSerializer):
    """
    Used by viewer.html — no authentication required.
    Accepts kit_id as a string and resolves to the Kit FK.
    """
    kit_id = serializers.CharField(write_only=True)

    class Meta:
        model  = Report
        fields = [
            'kit_id',
            'reporter_nom', 'reporter_prenom', 'reporter_service',
            'severity', 'message',
        ]

    def validate_kit_id(self, value):
        try:
            self._kit = Kit.objects.get(kit_id=value)
        except Kit.DoesNotExist:
            raise serializers.ValidationError(f'No kit found with id "{value}".')
        return value

    def create(self, validated_data):
        validated_data.pop('kit_id')
        return Report.objects.create(
            kit=self._kit,
            kit_name_snapshot=self._kit.kit_name,
            **validated_data
        )


class ReportAdminSerializer(serializers.ModelSerializer):
    """Full report detail for admin dashboard."""

    class Meta:
        model  = Report
        fields = '__all__'
